### ISSUE TITLE
Examples return 404

### ISSUE THREAD

**Issue by Kartstig** [dryruby/ebnf#14]
**Describe the bug**
I think the example links may need updating

**To reproduce**
1. Click on any example link in README or on docs website
2. See 404 error

**Expected behavior**
HTTP 200

**Screenshots**
![image](https://user-images.githubusercontent.com/2031422/180083832-92c42bed-ba28-4c0b-8d35-9626a6c4f2cc.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by gkellogg** [comment]
I suspect a YARD configuration issue, which is causing the examples to not be added, which may require some post-processing to get the files in place. Thanks for pointing this out.

**Comment by gkellogg** [comment]
This should be largely fixed now, although some of the formatting varies between the generated Yard documentation and the view of the README in the project directory.

**Comment by Kartstig** [comment]
@gkellogg I can confirm it's working. Thanks for the quick response!
